[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solady/src/=lib/solady/src/",
    "@forge-std/src/=lib/forge-std/src/",
]

[invariant]
runs = 1215
depth = 500
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
